### PR TITLE
Update fvp.rst

### PR DESCRIPTION
**Pull request by PandaQ2014**
Necessary configurations to change FVP Foundation Model to Base Model

### CODE REVIEW

**Comment by jforissier** [comment]
That looks useful, but in my opinion it would be better (easier to use and maintain) to modify `fvp.mk` to support both the Foundation Platform and the Base Model. For instance, introduce a build variable, say `BASE_MODEL`. When non-empty you would use an alternate rule for `run-only`, change the path to the DT source,  use a different `grub.cfg` etc.

**Comment by PandaQ2014** [comment]
> That looks useful, but in my opinion it would be better (easier to use and maintain) to modify `fvp.mk` to support both the Foundation Platform and the Base Model. For instance, introduce a build variable, say `BASE_MODEL`. 

I agree with you :joy:

**Comment by jbech-linaro** [comment]
> > That looks useful, but in my opinion it would be better (easier to use and maintain) to modify `fvp.mk` to support both the Foundation Platform and the Base Model. For instance, introduce a build variable, say `BASE_MODEL`.
> 
> I agree with you

So, we should close the ticket?

**Comment by PandaQ2014** [comment]
> > > That looks useful, but in my opinion it would be better (easier to use and maintain) to modify `fvp.mk` to support both the Foundation Platform and the Base Model. For instance, introduce a build variable, say `BASE_MODEL`.
> > 
> > 
> > I agree with you
> 
> So, we should close the ticket?

OK

**Pull request closed without merging**
