### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by akorb**
Simple typo fix.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Thanks, please finalize the commit message according to [this](https://optee.readthedocs.io/en/latest/general/contribute.html).
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by akorb** [comment]
Did I do it right?

**Comment by jbech-linaro** [comment]
> Did I do it right?

Almost, you forgot your own Signed-Off-By, otherwise it's all good, thanks!

**Comment by jbech-linaro** [comment]
Perfect, thank you!

**Pull request merged**
