### PR TITLE
config: extend Copyright date

### PR DESCRIPTION
**Pull request by ldts**
as every year

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by ldts** [comment]
@jbech-linaro tag added

**Comment by ldts** [comment]
wondering if we should just remove the copyright notice...instead of doing this silly PRs...

**Comment by jforissier** [comment]
> wondering if we should just remove the copyright notice...instead of doing this silly PRs...

According to https://techwhirl.com/updating-copyright-notices/ (which only mentions US law BTW):
1. Copyright notices are not required for copyright protection to be enforceable
2. The date is the year of first publication of the work and does not need to be updated, although it is common practice to do so

If it were just me to decide I would have kept `copyright = '2019 Linaro'` and never modified it.

**Comment by jbech-linaro** [comment]
I'll merge this, but as stated by Jerome, we don't have to update the year in the future. Thanks!

**Pull request merged**
