### PR TITLE
Update prerequisites.rst

### PR DESCRIPTION
**Pull request by cevatbostancioglu**
rsync dependency error solved.

### CODE REVIEW

**Comment by jforissier** [comment]
Hi @cevatbostancioglu,

LGTM, but would you mind quoting what error this fixes?

**Comment by cevatbostancioglu** [comment]
Hi @jforissier , Thanks for reply.

Platform: Docker container, inherited from Ubuntu 16.04
$ uname -a
Linux CevatsContainer 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Error:

make[1]: Entering directory '/opt/optee/buildroot'
mkdir -p /opt/optee/out-br/build/buildroot-config/lxdialog
PKG_CONFIG_PATH="" make CC="/usr/bin/gcc" HOSTCC="/usr/bin/gcc" \
    obj=/opt/optee/out-br/build/buildroot-config -C support/kconfig -f Makefile.br conf
/usr/bin/gcc -D_GNU_SOURCE -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/optee/out-br/build/buildroot-config -DCONFIG_=\"\"  -MM *.c > /opt/optee/out-br/build/buildroot-config/.depend 2>/dev/null || :
/usr/bin/gcc -D_GNU_SOURCE -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/optee/out-br/build/buildroot-config -DCONFIG_=\"\"   -c conf.c -o /opt/optee/out-br/build/buildroot-config/conf.o
/usr/bin/gcc -D_GNU_SOURCE -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/optee/out-br/build/buildroot-config -DCONFIG_=\"\"  -I. -c /opt/optee/out-br/build/buildroot-config/zconf.tab.c -o /opt/optee/out-br/build/buildroot-config/zconf.tab.o
/usr/bin/gcc -D_GNU_SOURCE -DCURSES_LOC="<ncurses.h>" -DLOCALE  -I/opt/optee/out-br/build/buildroot-config -DCONFIG_=\"\"   /opt/optee/out-br/build/buildroot-config/conf.o /opt/optee/out-br/build/buildroot-config/zconf.tab.o  -o /opt/optee/out-br/build/buildroot-config/conf
rm /opt/optee/out-br/build/buildroot-config/zconf.tab.c
  GEN     /opt/optee/out-br/Makefile
#
# configuration written to /opt/optee/out-br/.config
#
make[1]: Leaving directory '/opt/optee/buildroot'
make[1]: Entering directory '/opt/optee/out-br'
/usr/bin/make -j1 O=/opt/optee/out-br HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" syncconfig
make[3]: warning: -jN forced in submake: disabling jobserver mode.
  GEN     /opt/optee/out-br/Makefile
**You must install 'rsync' on your build machine**
support/dependencies/dependencies.mk:27: recipe for target 'dependencies' failed
make[2]: *** [dependencies] Error 1
Makefile:23: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/opt/optee/out-br'
common.mk:201: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

**Comment by jenswi-linaro** [comment]
We're using rsync in Buildroot to copy the optee_*.gits into the build directory.

**Comment by cevatbostancioglu** [comment]
- buildroot requires rsync package. checkout https://buildroot.org/downloads/manual/manual.html (2.1 mandatory packages). probably most of the packages are provided in the given pre-reqs list.
- alphabetical order done.

**Comment by jforissier** [comment]
@jenswi-linaro @cevatbostancioglu OK, I wasn't aware of that.

@cevatbostancioglu would you mind mentioning that buildroot requires rsync in your commit message?

Anyway:
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by cevatbostancioglu** [comment]
@jforissier 
- update commit message done.

**Comment by jbech-linaro** [comment]
I've totally missed that too. Thanks!
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by cevatbostancioglu** [comment]
@jbech-linaro @jforissier it's been a 1 week, do i have to do something else about this pr to be merged?

**Comment by jforissier** [comment]
Please add your `Signed-off-by:` tag and @jbech-linaro's `Reviewed-by:` tag.

**Comment by cevatbostancioglu** [comment]
@jforissier thanks for the response.

**Comment by jforissier** [comment]
Thanks. No blank line between the S-o-b: and R-b: tags please ;-)

**Comment by cevatbostancioglu** [comment]
@jforissier updated.

**Comment by jbech-linaro** [comment]
Thanks @cevatbostancioglu !

**Pull request merged**
