### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by jforissier**
A couple of fixes to the release procedure for minor issues that I noticed when doing 3.8.0.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
Tag applied.

**Comment by jenswi-linaro** [comment]
We don't we need signed tags?

**Comment by jforissier** [comment]
Why would we need signed tags when we don't have signed commits for instance?
I'm not against signing the tags, it's just that I don't have set up a key for that (I've never tried actually ;-))

**Comment by jenswi-linaro** [comment]
You can only sign tags, with a signed tag you know that a particular commit is authentic.
Compare with the kernel, Linus signs release (and RC tags). That allows you to pull the changes from any tree and trust it. Same thing with pull request which are sent to the kernel maintainers, all the tags communicated there are signed so the maintainer knows it's trusted. If only the sha-sums of the commits where mailed then mail would be the root of trust or even worse maybe some random tree somewhere.

**Comment by jforissier** [comment]
@jenswi-linaro what you say all makes sense of course, it's just that in our case the "root of trust" is Github. If I, or someone else with admin rights, could push the tag to Github in the first place, it means it is authentic. I agree it's not as good as a signed tag since the authenticity is not "self contained" in the tag (one would need to check Github to authenticate the tag).

You know what? I'm going to set up some GPG keys for myself. Maybe in the future I can create signed tags ;-)

**Comment by jenswi-linaro** [comment]
Sounds good, let's leave the signing for the next time.

**Comment by jbech-linaro** [comment]
So, we're all happy with these commits? Or do we want to revert the "-s"?

**Comment by jforissier** [comment]
No strong opinion for me, I can push a commit that adds the "-s" where it is missing instead, since it is the direction we want to take.

**Comment by jenswi-linaro** [comment]
Doesn't matter to me.

**Comment by jbech-linaro** [comment]
Let's keep it as it is.

**Pull request merged**
