### PR TITLE
Update rpi3.rst

### PR DESCRIPTION
**Pull request by kunmukh**
Updated the documentation to reflect RPi 3 Model B has support and RPi 4 does not have support

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
@kunmukh , I need you signed-off by tag to be able to merge this. Run "git log" and check the other commits and you'll figure out what I'm asking for.

**Comment by kunmukh** [comment]
This is my first time doing something like this. So, I just want to make sure, that I am adding this comment(I just rewrote my commit message based on the previous git log message)?

"Update optee_docs documentation    
Updated the documentation to reflect RPi 3 Model B has support and RPi 4 does not have support    
Signed-off-by: Kunal Mukherjee <kunmukh@gmail.com>"

**Comment by jbech-linaro** [comment]
Something like this:

```commit
rpi: update documentation regarding RPi4

RPi4 is not yet supported in the official builds coming from the OP-TEE project,
update the table of supported RPi devices to reflect that.

Signed-off-by: Kunal Mukherjee <kunmukh@gmail.com>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
```
If you haven't done it before, then it could be worth to mention that you simply could amend the commit message (`git commit --amned`), then you sometime need to rebase it against master (`git rebase origin/master`). Lastly, force push the commit to your branch again (`git push -f <my-branch>:<my-branch-at-github>`).

**Comment by kunmukh** [comment]
I think, I did it? Thank you, for being so helpful.

**Comment by jbech-linaro** [comment]
Thanks, looking good, closing (patch manually merged)!

**Pull request closed without merging**
