### PR TITLE
building: qemu: added hints about repo and make

### PR DESCRIPTION
**Pull request by johndoe31415**
Using QEemu to debug on branches is a useful feature and possibly not obvious to people not familiar with "repo". People unfamiliar with "make" might not know about parallel builds. Include hints about both.

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
@johndoe31415 , can you please add Jerome's Acked-by tag to the commit? Once done, I will merge, thanks!

**Comment by johndoe31415** [comment]
@jbech-linaro Did that yesterday, have force pushed it on my branch.

**Comment by jbech-linaro** [comment]
Hi @johndoe31415 , sorry for the delay, we need your own Signed-off-by tag as well, please run git log and you'll see what I'm asking for.

**Comment by johndoe31415** [comment]
No worries. Done!

**Pull request merged**
