### PR TITLE
prerequisites: list both python 2 and 3 packages

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
@hzhuang1 fyi

**Comment by hzhuang1** [comment]
Maybe you need to replace "python-serial" by "python3-serial" in the same change set.
As my understanding, "python" is only for python2. The command include packages for both python2 and python3. It's not good.

**Comment by vchong** [comment]
I did try to search for python3-serial but it seems like there's no such package.

**Comment by vchong** [comment]
Found it on 'apt search' though. Will update. Thanks

**Comment by jbech-linaro** [comment]
> As my understanding, "python" is only for python2.

Most of that is true, but I think there are distro's where "python" actually means python3. I think this was the case when I was running Arch Linux. Having said that, our instructions in the docs is for Ubuntu, so the proposed patch here is correct IMHO.

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
What script uses python-serial? How is python invoked in that script? Has it been migrated to python3? My concern is, if the script invokes `python` on a distribution that links `python` to `python2`, then installing `python3-serial` won't work, right?

**Comment by vchong** [comment]
To cover both versions and use cases, should we just include both the python-* and python3-* packages? It is a 1 time install only so the cost isn't really that high.

**Comment by vchong** [comment]
Both the python-* and python3-* packages have been listed.
Tag has been added as well.
@jbech-linaro please merge if ok, else comment on changes required. Thanks!

**Comment by jbech-linaro** [comment]
I'm fine with it and it's not the first package that we have listed "twice". We can (and probably should) clean this up later when Python 3 only has got wider acceptance. I'll merge.

**Pull request merged**
