### PR TITLE
platform: Add i.MX8M links

### PR DESCRIPTION
**Pull request by b49020**
Information added in this patch is taken from corresponding patch in
OP-TEE/optee_os, commit ID: 42615b81f3f7.

@OP-TEE/plat-imx: please help to confirm validity of information added as part of this patch.

### CODE REVIEW

**Comment by MrVan** [comment]
Reviewed-by: Peng Fan <peng.fan@nxp.com>

**Comment by b49020** [comment]
Tag applied.

**Comment by b49020** [comment]
Is there anything pending to get this PR merged?

**Comment by jbech-linaro** [comment]
All good @b49020 , I've just missed this one, so thanks for reminding me. I'll merge.

**Pull request merged**
