### PR TITLE
Fixes GP API revision numbers

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
Review tag applied.
I've also added `Fixes: https://github.com/OP-TEE/optee_os/issues/6134` tag in 1st commit message.

Please consider this P-R for next OP-TEE tag.

**Review by zjchen666 — APPROVED** [review]

**Comment by zjchen666** [comment]
Acked-by: Zhijun Chen <tjuchenzj@gmail.com>

**Comment by zjchen666** [comment]
`Acked-by: Zhijun Chen <zhijunc@netflix.com>`

**Comment by etienne-lms** [comment]
Thanks @zjchen666, review tag applied.

**Comment by jbech-linaro** [comment]
Thanks @etienne-lms , all! Merging!

**Pull request merged**
