### PR TITLE
Add python3-pycryptodome to requirements

### PR DESCRIPTION
**Pull request by chrysh**
Signed-off-by: Christina Quast <contact@christina-quast.de>

### CODE REVIEW

**Comment by jforissier** [comment]
This is mostly correct but I remember there are issues with older Ubuntu distributions (16.*), like you need a PIP package named pycryptodomex (note the "x" at the end). @jbech-linaro I think you had a pretty good replacement for this prerequisite section?

**Comment by jbech-linaro** [comment]
@chrysh  solution is "the most" correct solution for recent distros. For older distros one one need to pull it as a pip package. For Ubuntu 16.04 for example I had to do:
```
python3 -m pip install --user pycryptodome
```
So, @chrysh please act on Jens comment (add tag and sort it it order) and then we can get this merged, thanks!

**Comment by chrysh** [comment]
I corrected to commit.

**Comment by jbech-linaro** [comment]
> @jbech-linaro I corrected to commit.

Thanks, would you mind please also add Jens review-by tag? (see the git log for how this should look like).

**Comment by chrysh** [comment]
Ok, I have done that and pushed!

**Comment by jbech-linaro** [comment]
Thanks a lot @chrysh for the patch!

**Comment by jforissier** [comment]
>  For Ubuntu 16.04 for example I had to do:
> 
> ```
> python3 -m pip install --user pycryptodome
> ```
> 
Ubuntu 16.04.6 LTS here, this command failed with an error about "no module pip" or something like that (sorry I have not copied the exact error). What worked for me:

```
sudo apt install python3-pip
pip3 install --user pycryptodomex
```

`pip3 install --user pycryptodome` does **not** work, it is the **x** package that is needed.

**Comment by jbech-linaro** [comment]
I don't know what is right and wrong, seems like different people get different results, [this](https://github.com/jbech-linaro/docker_optee/blob/cached-ubuntu-16.04/Dockerfile) is the Docker file that I did put together 3 months ago. It's based on Ubuntu 16.04 and there I have both the "python3-pip" apt package and then a separate pip install for the crypto stuff (`RUN python3 -m pip install --user pycryptodome`). Perhaps they've upgrade the 16.04 image since what I used three months ago?

**Comment by jbech-linaro** [comment]
And for reference [here](https://github.com/jbech-linaro/docker_optee/blob/cached/Dockerfile) is my Dockerfile for `ubuntu-latest`.

**Pull request merged**
