### PR TITLE
Sphinx panels

### PR DESCRIPTION
**Pull request by jbech-linaro**
This adds the missing configuration to be able to render #186 . Since I was doing documentation changes I took the opportunity to also fix some existing warnings and errors.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
So, readthedocs ends with
```
Extension error:
Could not import extension sphinx_panels (exception: No module named 'sphinx_panels')
```
Means that I need to investigate this more. Locally things built as expected.

**Comment by jbech-linaro** [comment]
> 

Managed to find the magic combination. In short, pinned the sphinx version to the same as I have on my Ubuntu 22.04, then I removed the version from sphinx-tabs. So, I think we're good to go now.

Squashed, rebased and tag(s) applied (should be) ready for merge! Thanks!

**Review by jforissier — COMMENTED** [review]
> conf: add support for sphinx-panels
> 
[...]
> Fixes: https://github.com/OP-TEE/optee_docs/pull/186

If I would want to split hairs I'd say it is not really a fix because nothing is broken at this point so perhaps `Link:` would be better.
> 
> Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

Anyways FWIW:

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
> If I would want to split hairs I'd say it is not really a fix because nothing is broken at this point so perhaps `Link:` would be better.

I was actually thinking about it, since I was afraid that having it as a "Fixed" might just close the other one. I'll change it to "Link:" instead, that is indeed better, thanks!

**Pull request merged**
