### PR TITLE
Build documentation touchup

### PR DESCRIPTION
**Pull request by sander-visser**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Thanks! Please add mig Signed-off by tag to the commit and force push again.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by sander-visser** [comment]
The pull req contained 2 separate commits.Should I add it to both, or should I squash despite isolated areas? Or should it have beed a separate pull req for the copy paste error?Iv added your reviewed by on the larger commit for now...Regards SanderDen 21 apr. 2020 12:23 skrev Joakim Bech <notifications@github.com>:
Thanks! Please add my Signed-off by tag to the commit and force push again.
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>

**Comment by sander-visser** [comment]
> Thanks! Please add my Signed-off by tag to the commit and force push again.
> `Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

The pull req contained 2 separate commits.

Should I add it to both, or should I squash despite isolated areas, or should it have been a separate pull req for the copy paste oneliner?

I have added your reviewed by on the larger commit for now...

**Comment by jbech-linaro** [comment]
I'm not too picky on that in this case, it's two different things so keeping two patches is fine I think. Add the tag to both and force push and then I'll merge.

**Comment by sander-visser** [comment]
> I'm not too picky on that in this case, it's two different things so keeping two patches is fine I think. Add the tag to both and force push and then I'll merge.

review tag now added to both commits

**Comment by sander-visser** [comment]
> I'm not too picky on that in this case, it's two different things so keeping two patches is fine I think. Add the tag to both and force push and then I'll merge.

review tag now added to both commits

**Comment by sander-visser** [comment]
re-opened after unverified force push that was not picked up by github (reviewed by tag added)

**Comment by sander-visser** [comment]
re-opened as #71 after unverified force push that was not picked up by github (reviewed by tag added)

**Pull request closed without merging**
