### PR TITLE
Add missing period

### PR DESCRIPTION
**Pull request by siddhesh**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
@siddhesh , please add my R-B tag to the commit and then we can get this merged.

**Comment by siddhesh** [comment]
Done.

**Comment by jbech-linaro** [comment]
Manually merged (Signed-off by was also missing, so I added you as Suggested-by instead and added a bit more context to the commit message).

**Pull request closed without merging**
