### PR TITLE
Typo quickfix in TA signing section

### PR DESCRIPTION
**Pull request by jclsn**
Seems like I overlooked two double quotes

### CODE REVIEW

**Comment by jclsn** [comment]
Sorry, was on holidays :) Like this?

**Comment by etienne-lms** [comment]
Yes, thanks.
@jbech-linaro, okay to merge?

**Comment by jbech-linaro** [comment]
Btw, I got an email about an Sphinx error after merging this. It's not an issue for this particular PR, it's probably more recent requirements from readthedocs.io. I'll look into it, but until we've sorted this out, the fix here will not show up on the official and rendered documentation. Just an FYI.

**Comment by jbech-linaro** [comment]
Issues should be fixed with --> https://github.com/OP-TEE/optee_docs/pull/231

**Pull request merged**
