### PR TITLE
presentations: add links to LVC20 presentations

### PR DESCRIPTION
**Pull request by jbech-linaro**
Update the presentation page with three relevant presentations from the
LVC20 Linaro Connect.

- LVC20-112 - PSA Secure Partitions in OP-TEE
- LVC20-118 - SCMI server in TEE
- LVC20-204 - Encrypted firmwares and how to bake them right

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Ruchika noticed that SAN19 is missing. I will add those to this PR as well.

**Comment by ruchi393** [comment]
Thanks @jbech-linaro

**Comment by jbech-linaro** [comment]
@ruchi393 please find the relevant SAN19 presentations as well.

**Comment by ruchi393** [comment]
`Acked-by: Ruchika Gupta <ruchika.gupta@linaro.org>`

**Pull request merged**
