### PR TITLE
Update core.rst

### PR DESCRIPTION
**Pull request by muxneo**
Small typo correction

### CODE REVIEW

**Comment by jforissier** [comment]
S-o-b: needed for doc PRs too?

**Comment by jbech-linaro** [comment]
> S-o-b: needed for doc PRs too?

I'm doing that manually (and reset author), since this patch is so tiny. Will push in a couple of seconds.

**Comment by jbech-linaro** [comment]
Manually merged (tweaked commit message a bit).

**Comment by muxneo** [comment]
thanks

**Pull request closed without merging**
