### PR TITLE
platform: Add newly added Renesas RZ/G platform

### PR DESCRIPTION
**Pull request by prabhakarlad**
Update the platform list to include the Renesas RZ/G platform.

Signed-off-by: Lad Prabhakar <prabhakar.mahadev-lad.rj@bp.renesas.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Thanks @prabhakarlad , I haven't followed this closely, but I cannot find the platform `RZG` in optee_os? Have I missed it or is it  not existing? If the latter, then this I can't merge this, since the list should only contain platforms that are supported.

**Comment by jbech-linaro** [comment]
Sorry for the noise, found it after checking out latest.

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by prabhakarlad** [comment]
> Sorry for the noise, found it after checking out latest.
> 
> `Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

Thanks for the RB tag.

Not sure why the CI build is taking such a while.

**Comment by jbech-linaro** [comment]
> Not sure why the CI build is taking such a while.

Neither do I, but I've seen that Travis been taking quite a bit of time recently. But this is rather an extreme case.

**Comment by prabhakarlad** [comment]
@jbech-linaro - request to merge.

**Comment by jbech-linaro** [comment]
I was waiting for you to add my Reviewed-by tag ([docs](https://optee.readthedocs.io/en/latest/general/contribute.html#finalizing-your-contribution)). Can you please just add that and force-push? Then I'll merge.

**Comment by prabhakarlad** [comment]
> I was waiting for you to add my Reviewed-by tag ([docs](https://optee.readthedocs.io/en/latest/general/contribute.html#finalizing-your-contribution)). Can you please just add that and force-push? Then I'll merge.

Sure will do that.

**Comment by jbech-linaro** [comment]
Thanks @prabhakarlad , merged!

**Pull request merged**
