### PR TITLE
Shift the release date for 3.16.0

### PR DESCRIPTION
**Pull request by ruchi393**
The current release date clashes with holiday season where
all maintainers may not be available for release testing. Shift
the release by 2 weeks to take care of this.

Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by ruchi393** [comment]
@jbech-linaro , can we merge this ?

**Comment by jbech-linaro** [comment]
Thanks for the reminder, merged!

**Pull request merged**
