### PR TITLE
Add Rock Pi 4

### PR DESCRIPTION
**Pull request by TaihuLight**

### CODE REVIEW

**Comment by TaihuLight** [comment]
add Rock Pi 4

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
@TaihuLight , can you please add my reviewed-by tag so I can merge this?

**Comment by TaihuLight** [comment]
@jbech-linaro Sorry, I do not how to add the tag, could you merge this directly?

**Comment by jforissier** [comment]
@TaihuLight this means adding Joakim's `Reviewed-by:` tag to the commit description (which is missing by the way, as well as your `Signed-off-by:`).

```
Add Rock Pi 4

Add the Rock Pi 4 board to the supported platforms.

Signed-off-by: Your Name <your.email@somedomain.com>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
```

See https://optee.readthedocs.io/en/latest/general/contribute.html

**Review by TaihuLight — COMMENTED** [review]
Add Rock Pi 4

Add the Rock Pi 4 board to the supported platforms.

Signed-off-by: Your Name <your.email@somedomain.com>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>

**Review by TaihuLight — COMMENTED** [review]
Add Rock Pi 4

Add the Rock Pi 4 board to the supported platforms.

Signed-off-by: Your Name <your.email@somedomain.com>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>

**Pull request closed without merging**
