### PR TITLE
Add cpio to the prerequisites

### PR DESCRIPTION
**Pull request by LuminousXLB**
This is required but not included in the documentation

### CODE REVIEW

**Review by jbech-linaro — APPROVED** [review]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.
@LuminousXLB, could you add description lines and Signed-of-by tag in the commit message? Something like:
```
building: prerequisite: add cpio

Adds cpio to prerequisite host package list.

Signed-of-by: ....
Reviewed-by: ...
```

**Comment by LuminousXLB** [comment]
Thanks @etienne-lms , the commit message is modified

**Comment by jbech-linaro** [comment]
Manually merged (fixed Signed-off-by spelling in the commit message), thanks!

**Pull request closed without merging**
