### PR TITLE
building: update offline signing doc

### PR DESCRIPTION
**Pull request by wamserma**
Update the instructions for offline signing to reflect the name
change of the signing script and the switch from PKCS#1.5 to PSS
as preferred RSA padding mode.

Signed-off-by: Markus S. Wamser <github-dev@mail2013.wamser.eu>

### CODE REVIEW

**Comment by wamserma** [comment]
see also https://github.com/OP-TEE/optee_os/issues/4081

**Comment by jforissier** [comment]
Thanks for the patch :+1: As far as I can tell this looks fine so:

`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by wamserma** [comment]
@jenswi-linaro care to merge?

**Comment by jbech-linaro** [comment]
Thanks @wamserma !

**Pull request merged**
