### PR TITLE
Drop benchmark

### PR DESCRIPTION
**Pull request by igoropaniuk**
Remove documentation about Benchmark Framework as current implementation is non-function and obsolete, and it's not supported anymore.

### CODE REVIEW

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Review by jbech-linaro — COMMENTED** [review]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
@jenswi-linaro @jbech-linaro tags applied and rebased. thanks

**Comment by jbech-linaro** [comment]
I could wait until it's actually is gone, but since I expect this happening shortly anyways. I'll go a head and merge this right away. Thanks Igor!

**Pull request merged**
