### PR TITLE
architecture: spmc: document SP loading mechanisms

### PR DESCRIPTION
**Pull request by balint-dobszay-arm**
Recently a new mechanism was introduced to the optee_os SPMC component, which enables loading SP packages generated by TF-A and loaded from the FIP. Update the documentation to reflect these changes.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by balint-dobszay-arm** [comment]
Can we get this merged please? Or is the someone else who would like to do a review?

**Comment by jbech-linaro** [comment]
@balint-dobszay-arm , thanks for the reminder, I'll merge it right away.

**Comment by balint-dobszay-arm** [comment]
Thanks!

**Pull request merged**
